name: 'Setup'
description: Setup
runs:
  using: "composite"
  steps:
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24'
        channel: stable
        cache: true
