name: widgetbook_workspace
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  widgetbook: ^3.10.0
  widgetbook_annotation: ^3.2.0
  flutter:
    sdk: flutter
  poke:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  widgetbook_generator: ^3.9.0

flutter:
  uses-material-design: true
